/**
 * llama_bridge_glue.js
 *
 * Browser-side WASM glue for the llama bridge.
 *
 * This file is generated/overwritten by Emscripten when `task build-wasm` runs.
 * It provides the JavaScript interface between the browser and the compiled
 * llama.cpp + bridge WebAssembly module.
 *
 * Upstream llama.cpp: https://github.com/ggml-org/llama.cpp
 *
 * Usage (after build):
 *   import LlamaBridge from './llama_bridge_glue.js';
 *   const module = await LlamaBridge();
 *   const handle = module._llama_chat_create(modelPathPtr, cbPtr, userDataPtr);
 *
 * NOTE: Do not edit this file manually — it is overwritten by `task build-wasm`.
 */

// Placeholder — replaced by Emscripten output after `task build-wasm`.
export default async function LlamaBridge() {
  throw new Error(
    'WASM module not built. Run: task build-wasm\n' +
    'Upstream: https://github.com/ggml-org/llama.cpp'
  );
}
